config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :workspaces do
    resources :bookings, only:[:new, :create]
  end
  resources :bookings, only: [:index, :destroy]
  root to: 'pages#home'
  get "/team", to:'pages#team'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :workspace

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :number_of_persons, presence: true

  NUMBER_OF_PERSONS = (1..10).to_a

  validate :valid_dates?


  def valid_dates?
    if end_date.present? && start_date.present? && end_date < start_date
      errors.add(:end_date, "can't be before start date")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_one_attached :photo
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  belongs_to :user
  validates :name, :description, :address, :capacity, :daily_rate, presence: true
  validates :daily_rate, numericality: { greater_than: 0 }
  validates :capacity, numericality: { only_integer: true }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_address_and_name,
    against: [ :address, :name ],
    using: {
      tsearch: { prefix: true }
    }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = Booking.where(user_id: current_user)
  end

  def show
  end

  def new
    @workspace = Workspace.find(params[:workspace_id])
    @booking = Booking.new
  end

  def create
    @booking = current_user.bookings.build(booking_params)
    @workspace = Workspace.find(params[:workspace_id])
    @booking.workspace = @workspace
    unless @booking.end_date.nil? || @booking.start_date.nil? || @booking.number_of_persons.nil?
      @booking.total_price = (@booking.end_date - @booking.start_date + 1) * @workspace.daily_rate * @booking.number_of_persons
    end

    @free = is_there_place?

    if @free == true 
      if @booking.save
        redirect_to bookings_path
      else
        render 'new'
      end
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to @booking
    else
      render 'edit'
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price, :number_of_persons)
  end

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def is_there_place?
    if @booking.valid?
      # Create an array of "dates" for each day booked
      date_array = (params[:booking][:start_date]..params[:booking][:end_date]).to_a
      # In this Array, we need to verify for each element = day, that the capacity is not exceeded
      date_array.all? do |date|
        # Extract all the bookings corresponding to this day, and to to the workspace
        bookings = Booking.where(
                                  "bookings.workspace_id = :workspace_id
                                  AND :date >= bookings.start_date
                                  AND :date <= bookings.end_date",
                                  workspace_id: params[:workspace_id],
                                  date: date
                                )
        # Sum all the persons of all the bookings of this day
        sum_bookings = bookings.sum(:number_of_persons)
        # Add the number_of_persons the user wants to book for
        new_sum_bookings = sum_bookings + params[:booking][:number_of_persons].to_i
        # Compares the future number of persons (if the booking is accepted) to the capacity of workspace
        new_sum_bookings <= Workspace.find(params[:workspace_id]).capacity
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def Team
  end
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  before_action :set_workspace, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = "address ILIKE :query OR name ILIKE :query"
      @workspaces = Workspace.where(sql_query, query: "%#{params[:query]}%")
    else
      @workspaces = Workspace.all
    end
    @markers = @workspaces.geocoded.map do |workspace|
      {
        lat: workspace.latitude,
        lng: workspace.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { workspace: workspace }),
        image_url: helpers.asset_url('https://www.flaticon.com/svg/static/icons/svg/1297/1297048.svg')
      }
    end
  end

  def show
    @markers =[{
        lat: @workspace.latitude,
        lng: @workspace.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { workspace: @workspace }),
        image_url: helpers.asset_url('https://www.flaticon.com/svg/static/icons/svg/1297/1297048.svg')
      }]
  end

  def new
    @workspace = Workspace.new
  end

  def create
    @workspace = Workspace.new(workspace_params)
    @workspace.user = current_user
    if @workspace.save
      redirect_to workspaces_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @workspace.update(workspace_params)
      redirect_to workspace_path
    else
      render 'edit'
    end
  end

  def destroy
    @workspace.destroy
    redirect_to workspaces_path
  end

  private

  def set_workspace
    @workspace = Workspace.find(params[:id])
  end

  def workspace_params
    params.require(:workspace).permit(:name, :description, :address, :capacity, :daily_rate, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="container mt-32"  >
  <div class="row d-flex justify-content-center mt-3">
    <div class="col-lg-3">
      <%= simple_form_for [@workspace, @booking] do |f| %>
          <%= f.input :start_date, as: :date, html5: true%>
          <%= f.input :end_date, as: :date, html5: true%>
        <%= f.input :number_of_persons, collection: Booking::NUMBER_OF_PERSONS, id:"number_of_persons" %>
        <% if  %>
        <div class="d-flex justify-content-center">
          <%= f.button :submit, "Submit", class: "btn btn-home btn-sm" %>
        </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-lg-3">
      <div class="d-flex justify-content-center my-3">
        <div class="card-booking">
          <%= cl_image_tag(@workspace.photo.key, crop: :fill) %>
          <div class="card-booking-title py-1">
          <%= link_to workspace_path(@workspace) do %>
            <h2 class="mb-1"><%= @workspace.name %></h2>
          <% end %>
            <p><i class="fas fa-users workspace-icon"></i> <span id="persons"></span> <%= @workspace.capacity %></p> 
          </div>
          <div class="card-booking-infos pt-1">
            <div>
              <small id="daily_rate"><%= @workspace.daily_rate %> CHF / day</small>
            </div>
            <h2 class="card-booking-pricing" id="computed_price"></h2>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-lg-5">
    </div>
  </div>
</div>

<% if @free == false %>
  <div class="flash flash-danger alert-center alert-dismissible fade show" role="alert">
    <span><strong>Oops!</strong> 😱 <br>it looks like the workspace is full at these dates</span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

<% if @empty == true %>
  <div class="flash flash-danger alert-center alert-dismissible fade show" role="alert">
    <span><strong>Oops!</strong> 😱 <br>Please fill all the fields</span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Edit Bookings</h1>

<%= render 'form' %>

app/views/bookings/index.html.erb
<div class="heading">
  <%= link_to "<<<", workspaces_path, class:"btn btn-back" %>
  <h2 class="u-center-text">My bookings</h2>
</div>
<div class="container pd-btm-lg">
  <div class="cards-booking mg-tp-md">
    <% @bookings.each do |booking| %>
      <div class="card-booking">
        <%= link_to "+", booking_path(booking), method: :delete, remote:true, class: "card-remove-link", data: {confirm: 'Are you sure you want to cancel this booking'} %>
        <%= cl_image_tag(booking.workspace.photo.key, crop: :fill) %>
        <div class="card-booking-title py-1">
        <%= link_to workspace_path(booking.workspace) do %>
          <h2 class="mb-1"><%= booking.workspace.name %></h2>
        <% end %>
          <p><i class="fas fa-users workspace-icon"></i> <%= booking.number_of_persons %></p> 
        </div>
        <div class="card-booking-infos pt-1">
          <div>
            <p><strong>from</strong> <%= booking.start_date.strftime("%a %d %b") %> <strong>to</strong> <%= booking.end_date.strftime("%a %d %b") %></p>
          </div>
          <h2 class="card-booking-pricing"><%= booking.total_price %> CHF</h2>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="heading">
  <%= link_to "<<<", workspaces_path, class:"btn btn-back" %>
  <h2 class="u-center-text">Create a booking</h2>
</div>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cowonthego</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render './shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render './shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="section background">
   <div class="section-center">
      <div class="container">
         <div class="row">
            <div class="main_div">
               <div class="booking-cta">
                  <h1>Find your coworking location</h1>
                  <p>  CowontheGo is your new partner to find the suitable workspace for you.</p>
                  <%= link_to 'Get started', workspaces_path, class:"btn btn-main" %>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/pages/team.html.erb
<div class="container mg-tp-md">
  <h1 class="mg-tp-md u-center-text mg-bt-sm">Our Team</h1>

    <div class="row u-margin-bottom-sm">
      <div class="col-md mr-3">
        <div class="d-flex align-items-center">
          <img class="avatar-large" alt="avatar-large" src="https://avatars1.githubusercontent.com/u/59468684?s=460&u=6cb043be59da4fa4c66a626e7e4e6404d821c37f&v=4" />
          <div class="pl-5">
            <h4>Simon Busch</h4>
            <hr>
            <p>After 8 years in the export business, travelling the world, Simon wanted to change sector and dive into coding to face new challenge and free his creativity.</p>
            <hr>
              <div class="footer-links">
                <a href="https://github.com/Simon-Busch" target="_blank"><i class="fab fa-github"></i></a>
                <a href="https://www.linkedin.com/in/simonbusch89/" target="_blank"><i class="fab fa-linkedin"></i></a>
              </div>
          </div>
        </div>
      </div>

      <div class="col-md mr-3">
        <div class="d-flex align-items-center">
          <img class="avatar-large" alt="avatar-large" src="https://avatars2.githubusercontent.com/u/72730792?s=460&u=9aeda3ffe37fbf809178c956240333d8d37ca15d&v=4" />
          <div class="pl-5">
            <h4>Tenzin Gasser</h4>
            <hr>
            <p>Freelance en graphisme et webdesign, je suis à recherche d'un renouveau et d'étendre mes notions dans le monde du développement afin d'être plus autonome.</p>
            <hr>
            <div class="footer-links">
              <a href="https://github.com/tenzgass" target="_blank"><i class="fab fa-github"></i></a>
              <a href="https://www.linkedin.com/in/tenzingasser/" target="_blank"><i class="fab fa-linkedin"></i></a>
            </div>          
          </div>
        </div>
      </div>
    </div>

    <div class="row u-margin-bottom-sm">
      <div class="col-md mr-3">
        <div class="d-flex align-items-center">
          <img class="avatar-large" alt="avatar-large" src="https://avatars2.githubusercontent.com/u/66464884?s=460&u=e13b5ce4c4512553ce3f474ac9ce9db44a7a0307&v=4" />
          <div class="pl-5">
            <h4>Benjamin Atieku Dzandu</h4>
            <hr>
            <p>After working in the engineering space for over 8 years, it's time to pivot into web developments. I have a deep passion for coding. My ultimate dream would be to have a startup that impacts the lives of ordinary people.</p>
            <hr>
            <div class="footer-links">
              <a href="https://github.com/KojoSwiss" target="_blank"><i class="fab fa-github"></i></a>
              <a href="https://www.linkedin.com/in/atieku/" target="_blank"><i class="fab fa-linkedin"></i></a>
            </div>  
          </div>
        </div>
      </div>

      <div class="col-md mr-3">
        <div class="d-flex align-items-center">
          <img class="avatar-large" alt="avatar-large" src="https://avatars2.githubusercontent.com/u/67010824?s=460&u=37630e834c389cd219c9e00e5ee8978997a79bd4&v=4" />
          <div class="pl-5">
            <h4>Eric Blandet</h4>
            <hr>
            <p>Hey, I'm Eric, 34 yo, and living in Lausanne! I've tried coding and I enjoy it. I am currenty studying @LeWagon but hope to work soon in a start-up to get some more experience in coding, while being able to ski as much as I can !</p>
            <hr>
            <div class="footer-links">
              <a href="https://github.com/ericblandet" target="_blank"><i class="fab fa-github"></i></a>
              <a href="https://www.linkedin.com/in/eric-blandet/" target="_blank"><i class="fab fa-linkedin"></i></a>
            </div>            
          </div>
        </div>
      </div>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/ericblandet/Cowonthego"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Cowonthego is created out of <i class="fas fa-fire"></i> by <%= link_to "iunGo group", team_path, class:"team-link" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/">
    <i class="fas fa-fire"></i>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <p>
  <span class="navbar-presentation" id="banner-typed-text"></span>
  </p>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
      <li><%= link_to "The team behind", team_path, class:"nav-link" %></li>
      <li><%= link_to "Workspaces",  workspaces_path , class: "nav-link" %> </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://randomuser.me/api/portraits/thumb/women/24.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "See my bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Create a workspace", new_workspace_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/workspaces/_form.html.erb
<div class="container mg-tp-md">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <%= simple_form_for @workspace do |f| %>
        <%= f.input :name, placeholder: 'IdeaFactory' %>
        <%= f.input :description, placeholder: 'A quiet space for the concentrated mind' %>
        <%= f.input :address, placeholder: '25 street Renens' %>
        <%= f.input :capacity, input_html: { min: '1', step: '1' } %>
        <%= f.input :daily_rate, placeholder: '$14.50', input_html: { min: '1', step: '1' } %>
        <%= f.input :photo, as: :file %>
        <div class=" h-centered">
        <%= f.button :submit, "Update", class: "btn btn-edit u-margin-bottom-md" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/workspaces/_info_window.html.erb
<div class="info_window">
  <h2><%= link_to workspace.name, workspace_path(workspace) %></h2>
  <p><%= workspace.address %></p>
  <div class="container_img">
    <% if workspace.photo.attached? %>
      <%= cl_image_tag workspace.photo.key, class:'info_window_img' %>
    <% end %>
  </div>
</div>

app/views/workspaces/edit.html.erb
<div class="heading mg-top-md">
  <%= link_to "<<<", workspaces_path, class:"btn btn-back" %>
  <h2 class=" u-center-text trslt-lft-sm">Edit your workspace</h2>
</div>
<%= render 'workspaces/form'%>

app/views/workspaces/index.html.erb
<div class="grid-index">
  <div class="grid-index-right">
    <div class="form-group form-index">
      <h2 class="search_heading mt-3">What location are you looking for ?</h2>
      <div class="search_input_main">
        <%= form_tag workspaces_path, class:"search_input", method: :get do %>
          <%= text_field_tag :query,
              params[:query],
              class: "form-control form-control-index",
              placeholder: "Enter a localisation"
          %>
          <%= submit_tag "Search", class: "btn btn-edit" %>
        <% end %>
      </div>
    </div>
    <section class="section-work mg-btm-hg">
      <% @workspaces.each do |workspace| %>
        <div class="card-grid">
          <a class="card" href= <%=workspace_path(workspace)%> >
            <% if workspace.photo.attached? %>
              <div class="card_background_active" style="background-image: url('<%= cl_image_path workspace.photo.key, height: 300, width: 400, crop: :fill%>')">
              </div> 
              <% else %>
                <div class="card_background"></div>
              <% end %>
              <div class="card_content">
                <h3 class="card_heading u-center-text"><%= workspace.name %></h3>
                <p class="card_category"><i class="fas fa-map-pin icon"></i><%= workspace.address %></p>
              </div>
            </a>
          </div>
      <% end %>
    </section>
  </div>

  <div class="grid-index-left">
    <div id="map"
      style="width: 33vw; height: 90vh;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      class="map_index">
    </div>
  </div>
</div>

app/views/workspaces/new.html.erb
<div class="heading-create ">
  <%= link_to "<<<", workspaces_path, class:"btn btn-back" %>
  <h2>Create a Workingspace </h2>
</div>
<%= render 'workspaces/form'%>

app/views/workspaces/show.html.erb
<div class ="grid-show">
  <div class="grid-left mg-btm-hg">
    <div class="heading-show mg-top-sm">
      <%= link_to "<<<", workspaces_path, class:"btn btn-back" %>
      <h2>Discover... </h2>
    </div>
    <div class="workspace-card">
      <div class="top">
        <div class="card-photo">
          <% if @workspace.photo.attached? %>
          <%= cl_image_tag @workspace.photo.key, class:'image_workspace' %>
          <% end %>
        </div>
        <div class="card-details">
        <h3 class="workspace_name u-center-text"><%= @workspace.name %></h3>
        <hr>
          <ul class="flexyflex">
            <li><i class="fas fa-map-pin workspace-icon"></i><%= @workspace.address %></li>
            <li><i class="fas fa-users workspace-icon"></i><%= @workspace.capacity %> Max </li>
            <li><i class="fab fa-bitcoin workspace-icon mg-btm-v-sm"></i><%= @workspace.daily_rate %>$ / Day</li>
            <hr>
            <li class="u-center-text">
              <% if current_user == @workspace.user%>
                <%= link_to "Edit Workspace", edit_workspace_path(@workspace), class:"btn btn-edit btn-center mg-right-md"  %>
                <%= link_to "Delete", workspace_path, method: :delete, data: {confirm: 'Are you sure?'}, class:"btn btn-edit btn-center"  %>
              <%end%>
            </li>
          </ul>
        </div>
      </div>
      <div class="bottom">
        <p class="description"><i class="fas fa-star workspace-icon"></i><%= @workspace.description %></p>
      </div>
      <div class="btn-center">
        <%= link_to "Book", new_workspace_booking_path(@workspace), class:"btn btn-home btn-booking" %>
      </div>
    </div>
  </div>
  <div class="grid-right">
    <div id="map"
      style="width: 33vw; height: 90vh;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>" class="map-img" >
    </div>
  </div>
</div>

    